from django.urls import path, include
from .views import (
    home,
    register,
    student_dashboard,
    faculty_dashboard,
    custom_logout,
    ajax_register,
    ajax_login,
    fetch_add_exam_form,
    fetch_edit_exam_form,
    delete_exam,
    cancel_exam,
    fetch_bookings_html,
    fetch_registration_html,
    get_exam_count,
    fetch_confirmation_html,
    queue_exam,
    confirm_queued_exam,
    update_exam,
    fetch_faculty_exam_grid,
    get_exam_data,
    add_exam,
    get_single_edit_exam_form,
    faculty_report_data,
    fetch_exam_students,
    get_dashboard_metrics
)

urlpatterns = [
    path('', home, name='home'),
    path('register/', register, name='register'),
    path("ajax/register/", ajax_register, name="ajax_register"),
    path("ajax/login/", ajax_login, name="ajax_login"),
    path('logout/', custom_logout, name='logout'),
    path('student/', student_dashboard, name='student_dashboard'),
    path("cancel_exam/<int:exam_id>/", cancel_exam, name="cancel_exam"),
    path('faculty/', faculty_dashboard, name='faculty_dashboard'),
    path('fetch_add_exam_form/', fetch_add_exam_form, name='fetch_add_exam_form'),
    path('fetch_edit_exam_form/', fetch_edit_exam_form, name='fetch_edit_exam_form'),
    path('faculty/exam/delete/<int:exam_id>/', delete_exam, name='delete_exam'),
    path("fetch_bookings_html/", fetch_bookings_html, name="fetch_bookings_html"),
    path('fetch_registration_html/', fetch_registration_html, name='fetch_registration_html'),
    path('fetch_confirmation_html/', fetch_confirmation_html, name='fetch_confirmation_html'),
    path('get_exam_count/', get_exam_count, name='get_exam_count'),
    path ('queue_exam/<int:exam_id>/', queue_exam, name='queue_exam'),
    path("confirm_queued_exam/<int:exam_id>/", confirm_queued_exam, name="confirm_queued_exam"),
    path("update_exam/<int:exam_id>/", update_exam, name="update_exam"),
    path("fetch_faculty_exam_grid/", fetch_faculty_exam_grid, name="fetch_faculty_exam_grid"),
    path("get_exam_data/<int:exam_id>/", get_exam_data, name="get_exam_data"),
    path("update_exam/<int:exam_id>/", update_exam, name="update_exam"),
    path("ajax_add_exam/", add_exam, name="ajax_add_exam"),
    path("get_single_edit_exam_form/<int:exam_id>/", get_single_edit_exam_form, name="get_single_edit_exam_form"),
    path("faculty/report/data/", faculty_report_data, name="faculty_report_data"),
    path('faculty/exam/<int:exam_id>/students/', fetch_exam_students, name='fetch_exam_students'),
path("get_dashboard_metrics/", get_dashboard_metrics, name="get_dashboard_metrics"),


]
