# Generated by Django 5.1.6 on 2025-02-12 03:28

from django.db import migrations, models
# Imports necessary for managing migrations and defining database models

class Migration(migrations.Migration):
    # This class represents a migration that modifies the database schema

    initial = True
    # Indicates this is the first migration for this app

    dependencies = [
        # No prior migrations required for this one
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            # Creates a new model called 'Item', which corresponds to a new database table
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # 'id' field serves as the primary key, with auto-increment enabled

                ('name', models.CharField(max_length=100)),
                # 'name' field is a short string with a maximum of 100 characters

                ('description', models.TextField()),
                # 'description' is a longer text field with no length limit

                ('created_at', models.DateTimeField(auto_now_add=True)),
                # 'created_at' stores the timestamp when the record was created, auto-set on creation
            ],
        ),
    ]
    # Defines the operations for the migration (in this case, creating the 'Item' model)