# Generated by Django 4.2.20 on 2025-04-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='frontend_user',
        ),
    ]
