# Generated by Django 5.1.6 on 2025-04-21 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_subject',
            field=models.CharField(default='Untitled Exam Subject', max_length=255),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='frontend.exam'),
        ),
    ]
