# Generated by Django 5.1.6 on 2025-04-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_exam_exam_subject_alter_examregistration_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('confirmed', 'Confirmed')], default='queued', max_length=10),
        ),
    ]
