# Generated by Django 5.1.6 on 2025-04-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_examregistration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='status',
        ),
    ]
